name: bump

on: [push]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
    - uses: tool3/bump@master
    - run: 'echo Hello'
      with:
        github_token: ${{ secrets.GP_TOKEN }}
        user: 'tal hayut'
        email: 'tal.hayut.dev@gmail.com'
