name: bump

on:
  push:
    branches:
    - master

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/bump@master
      with:
        github_token: ${{ secrets.GP_TOKEN }}
        user: 'Tal hayut'
        email: 'tal.dev@gmail.com'
