name: bump

on: [push]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - run: 'npm -v'
    - uses: tool3/bump@master
      with:
        github_token: ${{ secrets.GP_TOKEN }}
        user: 'T hayut'
        email: 'tal.dev@gmail.com'
