name: bump

on: [push]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - runs: 'npm -v'
    - uses: tool3/bump@master
    - runs: 'echo ${GITHUB_REF}'
      with:
        github_token: ${{ secrets.GP_TOKEN }}
        user: 'tal hayut'
        email: 'tal.hayut.dev@gmail.com'
