name: bump

on: [push]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@v1"
    - uses: tool3/bump@master
      with:
        github_token: ${{ secrets.GP_TOKEN }}
        user: 'T hayut'
        email: 'tal.dev@gmail.com'
